# Generated by Django 3.2 on 2022-12-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_2k',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_4k',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_hd',
        ),
    ]
