# Generated by Django 4.2.17 on 2026-02-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
